config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
    resources :comments, except: %i[index show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, :body, presence: true

  def self.paginate(page)
    limit(10).offset((page.to_i - 1) * 10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(params[:post_id]), status: :see_other }
        format.json { render json: @comment, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_path, status: :created, location: @comment }
        format.json { render json: @comment, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      format.html { redirect_to post_path(params[:post_id]), status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    search = params[:search]
    @posts = search.nil? ? Post.paginate(params[:page]) : Post.where('title LIKE ?', "%#{search}%").paginate(params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, status: :created, location: @post }
        format.json { render json: @post, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(@post), status: :see_other, location: @post }
        format.json { render json: @post, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @post.destroy
      format.html { redirect_to posts_path, status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_by_post(post)
    Comment.where(post_id: post)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def all_posts_count
    post_count = Post.all.count
    if post_count % 10 != 0
      post_count / 10 + 1
    else
      post_count / 10
    end
  end
end

app/views/comments/_comment.html.erb
<p>content: <%= comment.content %></p>

app/views/comments/_index.html.erb
<h4>Comments</h4>
<% comments_by_post(params[:id]).each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
<%= link_to 'Add Comment', new_post_comment_path(params[:id]) %>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: post_comments_path do |form| %>
    <% if @comment.errors.any? %>
    <h5 class="text-danger">Unable to save due to <%= pluralize(@comment.errors.count, 'error') %></h5>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><strong class="text-danger"><%= msg %></strong></li>
      <% end %>
    </ul>
  <% end %>
  <div class="field">
    <%= form.label :content, class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <%= form.submit 'Send' %>
<% end %>

app/views/layouts/_flash.html.erb
<% unless flash[:notice] %>
  <%= notice %>
<% end %>
<% unless flash[:alert] %>
  <%= alert %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class9Exercise1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <% if @post.errors.any? %>
    <h5 class="text-danger">Unable to save due to <%= pluralize(@post.errors.count, 'error') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><strong class="text-danger"><%= msg %></strong></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_field :body , class: 'form-control'%>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <h2>Title: <%= post.title %></h2>
  <p>Body: <%= post.body %></p>

  <%= link_to 'Expand this post', post_path(post) %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %></h1>

<%= render 'form' %>

<%= link_to 'Back to Posts', posts_path %>

app/views/posts/index.html.erb
<header class="d-flex">
<h1 class="me-4">Posts</h1>
<div class="mt-3">
  <%= form_with url: '/posts', method: :get do |form| %>
    <%= form.text_field :search, placeholder: 'Search by Title', class: 'me-2' %>
    <%= form.submit 'Search' %>
  <% end %>
</div>
</header>
<div class="d-flex">
  <% all_posts_count.times do |idx| %>
    <% page_number = idx + 1 %>
    <div class="m-2"><%= link_to page_number, posts_path(page: page_number) %></div>
  <% end %>
</div>

<%= link_to 'Add new post', new_post_path %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back to Posts', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<div class="d-flex">
  <%= button_to 'Edit Post', edit_post_path(@post), class: 'btn btn-secondary m-2', method: :get %>
  <%= button_to 'Delete Post', post_path(@post), class: 'btn btn-danger m-2', method: :delete %>
  <%= button_to 'Go back to Posts', posts_path, class: 'btn btn-primary m-2', method: :get %>
</div>
<div class="comments">
  <%= render 'comments/index' %>
</div>